In [10]:
import numpy as np
import scipy as sp
a = [[4,3],[3,4]]
a = np.array(a)
print(a)
l,V = np.linalg.eig(a)
print(V,l)
print(np.dot(V,np.dot(np.diag(l),V.conj().T)))
print(sp.linalg.logm(a))
print(np.log(7))

[[4 3]
 [3 4]]
[[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]] [7. 1.]
[[4. 3.]
 [3. 4.]]
[[0.97295507 0.97295507]
 [0.97295507 0.97295507]]
1.9459101490553132


In [13]:
from qiskit.opflow import X,Y,Z

l,V = np.linalg.eig(Y.to_matrix())
print(l,V)

[ 1.+0.j -1.+0.j] [[-0.        -0.70710678j  0.70710678+0.j        ]
 [ 0.70710678+0.j          0.        -0.70710678j]]


In [20]:
A = np.array([[1,0],[1,1]])
u,s,vh = sp.linalg.svd(A)
s = np.diag(s)
print(u)
print(s)
print(vh)
print(u @ s @ u)

[[-0.52573111 -0.85065081]
 [-0.85065081  0.52573111]]
[[1.61803399 0.        ]
 [0.         0.61803399]]
[[-0.85065081 -0.52573111]
 [-0.52573111  0.85065081]]
[[0.89442719 0.4472136 ]
 [0.4472136  1.34164079]]


In [22]:
A = np.array([[1,0],[1,1]])
u,p = sp.linalg.polar(A,'left')
print(u)
print(p)

[[ 0.89442719 -0.4472136 ]
 [ 0.4472136   0.89442719]]
[[0.89442719 0.4472136 ]
 [0.4472136  1.34164079]]
